-- MySQL Script generated by MySQL Workbench
-- Wed Aug 17 21:25:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UniversoLeitura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UniversoLeitura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UniversoLeitura` DEFAULT CHARACTER SET utf8 ;
USE `UniversoLeitura` ;

-- -----------------------------------------------------
-- Table `UniversoLeitura`.`ASSOCIADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`ASSOCIADOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rg` CHAR(7) NULL,
  `nome` VARCHAR(50) NULL,
  `sobrenome` VARCHAR(50) NULL,
  `endereco` VARCHAR(150) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`EMPRESTIMOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`EMPRESTIMOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_associado` INT NOT NULL,
  `date` DATE NULL,
  `prazo_devolucao` DATE NULL,
  `data_devolucao` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_EMPRESTIMO_ASSOCIADO_idx` (`id_associado` ASC) VISIBLE,
  CONSTRAINT `FK_EMPRESTIMO_ASSOCIADO`
    FOREIGN KEY (`id_associado`)
    REFERENCES `UniversoLeitura`.`ASSOCIADOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`EDITORAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`EDITORAS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(150) NULL,
  `telefone` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`TELEFONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`TELEFONES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone_socio` VARCHAR(100) NULL,
  `idAssociado` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_TELEFONES_ASSOCIADOS_idx` (`idAssociado` ASC) VISIBLE,
  CONSTRAINT `FK_TELEFONES_ASSOCIADOS`
    FOREIGN KEY (`idAssociado`)
    REFERENCES `UniversoLeitura`.`ASSOCIADOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`AUTORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`AUTORES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `sobrenome` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`LIVROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`LIVROS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cod_ISBN` VARCHAR(13) NULL,
  `titulo` VARCHAR(200) NULL,
  `ano_criacao` CHAR(4) NULL,
  `cod_autor` INT NULL,
  `ano_publicacao` CHAR(4) NULL,
  `cod_editora` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_LIVRO_AUTOR_idx` (`cod_autor` ASC) VISIBLE,
  INDEX `FK_LIVRO_EDITORA_idx` (`cod_editora` ASC) VISIBLE,
  CONSTRAINT `FK_LIVRO_AUTOR`
    FOREIGN KEY (`cod_autor`)
    REFERENCES `UniversoLeitura`.`AUTORES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LIVRO_EDITORA`
    FOREIGN KEY (`cod_editora`)
    REFERENCES `UniversoLeitura`.`EDITORAS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`EXEMPLARES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`EXEMPLARES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cod_livro` INT NULL,
  `sinistro` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_EXEMPLAR_LIVRO_idx` (`cod_livro` ASC) VISIBLE,
  CONSTRAINT `FK_EXEMPLAR_LIVRO`
    FOREIGN KEY (`cod_livro`)
    REFERENCES `UniversoLeitura`.`LIVROS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversoLeitura`.`EMPRESTIMO_EXEMPLARES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLeitura`.`EMPRESTIMO_EXEMPLARES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cod_emprestimo` INT NULL,
  `cod_exemplar` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_EMPRESTIMO_EXEPLAR_EMPRESTIMO_idx` (`cod_emprestimo` ASC) VISIBLE,
  INDEX `FK_EMPRESTIMO_EXEMPLAR_EXEMPLARES_idx` (`cod_exemplar` ASC) VISIBLE,
  CONSTRAINT `FK_EMPRESTIMO_EXEPLAR_EMPRESTIMO`
    FOREIGN KEY (`cod_emprestimo`)
    REFERENCES `UniversoLeitura`.`EMPRESTIMOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_EMPRESTIMO_EXEMPLAR_EXEMPLARES`
    FOREIGN KEY (`cod_exemplar`)
    REFERENCES `UniversoLeitura`.`EXEMPLARES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
