CREATE VIEW 
	FATURAS_NACIONAIS AS 
SELECT 
	faturas.ID, faturas.data_fatura, CLIENTES.ID, 
    clientes.nome, clientes.sobrenome, faturas.valor_total
FROM FATURAS
INNER JOIN CLIENTES ON CLIENTES.ID = FATURAS.ID_CLIENTE
WHERE PAIS_COBRANCA = 'Brazil';

SELECT * FROM FATURAS WHERE PAIS_COBRANCA =  'Brazil';

SELECT CLIENTES.NOME FROM CLIENTES WHERE ID = 10;

SELECT * FROM FATURAS_NACIONAIS;

